### PR TITLE
Retry strategy to attach listener to activity

### LINKED ISSUE #5: java.lang.RuntimeException: TouchThroughTouchHandlerInterface was not set on app activity
Hey Simon,

Is this the new "official" repo location? If so, got a crash report. Affects about 0.1% of our users in production. Any thoughts on root cause?

```
java.lang.RuntimeException: TouchThroughTouchHandlerInterface was not set on app activity

com.rome2rio.android.reactnativetouchthroughview.TouchThroughWrapper.setActivityListener TouchThroughWrapper.java:45
com.rome2rio.android.reactnativetouchthroughview.TouchThroughWrapper.<init> TouchThroughWrapper.java:20
com.rome2rio.android.reactnativetouchthroughview.TouchThroughWrapperManager.createViewInstance TouchThroughWrapperManager.java:18
com.rome2rio.android.reactnativetouchthroughview.TouchThroughWrapperManager.createViewInstance TouchThroughWrapperManager.java:7
com.facebook.react.uimanager.ViewManager.createView ViewManager.java:42
com.facebook.react.uimanager.NativeViewHierarchyManager.createView NativeViewHierarchyManager.java:260
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute UIViewOperationQueue.java:200
com.facebook.react.uimanager.UIViewOperationQueue$1.run UIViewOperationQueue.java:888
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches UIViewOperationQueue.java:1001
com.facebook.react.uimanager.UIViewOperationQueue.access$2400 UIViewOperationQueue.java:46
com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded UIViewOperationQueue.java:959
com.facebook.react.bridge.GuardedRunnable.run GuardedRunnable.java:24
android.os.Handler.handleCallback Handler.java:739
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:148
android.app.ActivityThread.main ActivityThread.java:5417
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:726
com.android.internal.os.ZygoteInit.main ZygoteInit.java:616
```

### PR DESCRIPTION
**Pull request by kristfal**
Not the most graceful attempt to fix #5

### CODE REVIEW

**Comment by kristfal** [comment]
Not tested as we can't really manage to trigger the race condition. 

We'll put this in production this week, will let you know how it fares.

**Comment by simonhoss** [comment]
Awesome. Thank you. I wait for your feedback then!

**Comment by kristfal** [comment]
@simonhoss no crashes in prod, nor any complaints about locked UIs any longer 🍏

**Comment by kristfal** [comment]
Got to backtrack on this one. We managed to reproduce it still. I’ll look into another fix.

**Comment by simonhoss** [comment]
Ok. Thank you for your investment!

**Pull request closed without merging**
